// Generated from art-room-curation.json by tmp/build_art_gallery.py.
// Only categorized works are included.
export const artCategoryOrder = [
  "Random stuff",
  "Colored stuff",
  "Cat",
  "Apartment",
  "Stuff I did when I was sick",
  "Black and white stuff",
  "Stuff I did for others"
];

export const artWorks = [
  {
    "id": "accf102caaa9",
    "index": 3,
    "title": "Nose",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/accf102caaa9.jpg",
    "aspect": 0.689167,
    "widthPx": 827,
    "heightPx": 1200
  },
  {
    "id": "dc0fb5fd452b",
    "index": 4,
    "title": "Man",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/dc0fb5fd452b.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "3fa24611db2e",
    "index": 33,
    "title": "Man",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/3fa24611db2e.jpg",
    "aspect": 0.7275,
    "widthPx": 873,
    "heightPx": 1200
  },
  {
    "id": "0841139f79ed",
    "index": 34,
    "title": "Girl",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/0841139f79ed.jpg",
    "aspect": 0.699167,
    "widthPx": 839,
    "heightPx": 1200
  },
  {
    "id": "151dc700225c",
    "index": 36,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/151dc700225c.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "7d1711faa978",
    "index": 37,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/7d1711faa978.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "9483107ce13a",
    "index": 38,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/9483107ce13a.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "d27bd2ae375f",
    "index": 39,
    "title": "Cycle",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/d27bd2ae375f.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "f1a9a33da84d",
    "index": 40,
    "title": "Man and cat",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/f1a9a33da84d.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "334bc46e37c1",
    "index": 41,
    "title": "Turn",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/334bc46e37c1.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "dfd49e17d7f1",
    "index": 46,
    "title": "Dog",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/dfd49e17d7f1.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "392cfca21f62",
    "index": 48,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/392cfca21f62.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "1468b88ced44",
    "index": 49,
    "title": "Face",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/1468b88ced44.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "24cc249637a8",
    "index": 51,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/24cc249637a8.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "0a92f6dedd2a",
    "index": 52,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/0a92f6dedd2a.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "1afd7c277b2c",
    "index": 53,
    "title": "Me",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/1afd7c277b2c.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "14f75fc15b2e",
    "index": 57,
    "title": "New Yorker",
    "category": "Random stuff",
    "note": "I moved to New York that day",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/14f75fc15b2e.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "b3a3b05e11ef",
    "index": 59,
    "title": "Orc",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/b3a3b05e11ef.jpg",
    "aspect": 0.75,
    "widthPx": 1200,
    "heightPx": 1600
  },
  {
    "id": "b46711f0f791",
    "index": 60,
    "title": "Orc",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/b46711f0f791.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "797679691fa5",
    "index": 71,
    "title": "Boy",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/797679691fa5.png",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "75471a4093c9",
    "index": 81,
    "title": "Dog",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/75471a4093c9.png",
    "aspect": 1.128881,
    "widthPx": 1200,
    "heightPx": 1063
  },
  {
    "id": "3cae410d137b",
    "index": 82,
    "title": "Cat",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/3cae410d137b.png",
    "aspect": 1.06383,
    "widthPx": 1200,
    "heightPx": 1128
  },
  {
    "id": "83ce7b37ed78",
    "index": 88,
    "title": "Wolf",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/83ce7b37ed78.png",
    "aspect": 1.807229,
    "widthPx": 1200,
    "heightPx": 664
  },
  {
    "id": "9e623bdcaf59",
    "index": 89,
    "title": "Guy",
    "category": "Random stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/9e623bdcaf59.png",
    "aspect": 1.043478,
    "widthPx": 1200,
    "heightPx": 1150
  },
  {
    "id": "3d6dadfae7e0",
    "index": 43,
    "title": "Man and cat",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/3d6dadfae7e0.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "0d215b9538e7",
    "index": 44,
    "title": "Circle",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/0d215b9538e7.jpg",
    "aspect": 0.985833,
    "widthPx": 1183,
    "heightPx": 1200
  },
  {
    "id": "f78195702d93",
    "index": 45,
    "title": "Robobear",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/f78195702d93.jpg",
    "aspect": 0.995833,
    "widthPx": 1195,
    "heightPx": 1200
  },
  {
    "id": "92cc62fdbaca",
    "index": 55,
    "title": "Sea",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/92cc62fdbaca.jpg",
    "aspect": 1.334816,
    "widthPx": 1200,
    "heightPx": 899
  },
  {
    "id": "fad46dd24f4b",
    "index": 58,
    "title": "Cloud",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/fad46dd24f4b.jpg",
    "aspect": 1.135289,
    "widthPx": 1200,
    "heightPx": 1057
  },
  {
    "id": "6a21ccda6a99",
    "index": 70,
    "title": "Pink lady",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/6a21ccda6a99.png",
    "aspect": 0.998333,
    "widthPx": 1198,
    "heightPx": 1200
  },
  {
    "id": "439db69efde5",
    "index": 78,
    "title": "Face",
    "category": "Colored stuff",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/439db69efde5.png",
    "aspect": 0.911667,
    "widthPx": 1094,
    "heightPx": 1200
  },
  {
    "id": "7b488391e1ba",
    "index": 79,
    "title": "Boy",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/7b488391e1ba.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "b0cd1ec1e029",
    "index": 80,
    "title": "Bee",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/b0cd1ec1e029.png",
    "aspect": 0.554167,
    "widthPx": 665,
    "heightPx": 1200
  },
  {
    "id": "f320009bb7fa",
    "index": 83,
    "title": "Characters",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/f320009bb7fa.png",
    "aspect": 1.7991,
    "widthPx": 1200,
    "heightPx": 667
  },
  {
    "id": "fish",
    "index": 10001,
    "title": "Fish",
    "category": "Colored stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/fish.jpg",
    "aspect": 1.046816,
    "widthPx": 1118,
    "heightPx": 1068
  },
  {
    "id": "41b2e8fa4484",
    "index": 13,
    "title": "Cat",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/41b2e8fa4484.jpg",
    "aspect": 1.265823,
    "widthPx": 1200,
    "heightPx": 948
  },
  {
    "id": "53c25e1f40c3",
    "index": 22,
    "title": "Cat mom",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/53c25e1f40c3.png",
    "aspect": 0.8475,
    "widthPx": 1017,
    "heightPx": 1200
  },
  {
    "id": "5052437336e9",
    "index": 32,
    "title": "cat",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/5052437336e9.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "1564dec85228",
    "index": 47,
    "title": "Three cat",
    "category": "Cat",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/1564dec85228.jpg",
    "aspect": 0.75,
    "widthPx": 1200,
    "heightPx": 1600
  },
  {
    "id": "744ad96fdc6b",
    "index": 56,
    "title": "Cat",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/744ad96fdc6b.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "cc66f73ca983",
    "index": 62,
    "title": "Cats",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/cc66f73ca983.jpg",
    "aspect": 0.74,
    "widthPx": 888,
    "heightPx": 1200
  },
  {
    "id": "d13471aa1235",
    "index": 63,
    "title": "Pierre",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/d13471aa1235.jpg",
    "aspect": 0.855,
    "widthPx": 1368,
    "heightPx": 1600
  },
  {
    "id": "ab50c28d9b81",
    "index": 66,
    "title": "Pierre",
    "category": "Cat",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/ab50c28d9b81.png",
    "aspect": 2.094241,
    "widthPx": 1200,
    "heightPx": 573
  },
  {
    "id": "db7627f9afb0",
    "index": 18,
    "title": "Bedroom",
    "category": "Apartment",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/db7627f9afb0.png",
    "aspect": 1.617251,
    "widthPx": 1200,
    "heightPx": 742
  },
  {
    "id": "55be41193e2e",
    "index": 19,
    "title": "Bookroom",
    "category": "Apartment",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/55be41193e2e.png",
    "aspect": 1.719198,
    "widthPx": 1200,
    "heightPx": 698
  },
  {
    "id": "618258b2743b",
    "index": 64,
    "title": "Living room",
    "category": "Apartment",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/618258b2743b.png",
    "aspect": 2.193784,
    "widthPx": 1200,
    "heightPx": 547
  },
  {
    "id": "apartment1",
    "index": 10002,
    "title": "my room in manhattan",
    "category": "Apartment",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/apartment1.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "apartment2",
    "index": 10003,
    "title": "my dorm on campus",
    "category": "Apartment",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/apartment2.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "b4e039e3a6cb",
    "index": 1,
    "title": "Feet outside blanket",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/b4e039e3a6cb.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "f20820c446c9",
    "index": 2,
    "title": "Fish tank",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/f20820c446c9.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "6b5ccd08dbb7",
    "index": 5,
    "title": "Buried fish",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/6b5ccd08dbb7.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "15be811bcd11",
    "index": 6,
    "title": "Alcohol",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/15be811bcd11.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "106f9f9afdba",
    "index": 9,
    "title": "Back pain",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/106f9f9afdba.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "834f6c772b80",
    "index": 10,
    "title": "Heavy",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/834f6c772b80.jpg",
    "aspect": 1.333333,
    "widthPx": 1200,
    "heightPx": 900
  },
  {
    "id": "eda737a6a706",
    "index": 11,
    "title": "Air tight",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/eda737a6a706.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "9b32fe60db5c",
    "index": 14,
    "title": "Fish",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/9b32fe60db5c.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "6a8c2d597fbc",
    "index": 15,
    "title": "Fish",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/6a8c2d597fbc.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "42ba1112516c",
    "index": 16,
    "title": "Belly pain",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/42ba1112516c.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "446166ff32dc",
    "index": 17,
    "title": "Loud",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/446166ff32dc.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "43b991bb27b1",
    "index": 20,
    "title": "Dark",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/43b991bb27b1.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "51caeb88de73",
    "index": 21,
    "title": "Trapped",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/51caeb88de73.jpg",
    "aspect": 0.958333,
    "widthPx": 1150,
    "heightPx": 1200
  },
  {
    "id": "09ee3ec1343e",
    "index": 23,
    "title": "Phone call",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/09ee3ec1343e.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "d9e18431651b",
    "index": 25,
    "title": "New York subway",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/d9e18431651b.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "42fda1c306ba",
    "index": 26,
    "title": "Corner",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/42fda1c306ba.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "68041d9481cc",
    "index": 27,
    "title": "Stuck",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/68041d9481cc.jpg",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "fd008607e991",
    "index": 31,
    "title": "ICU",
    "category": "Stuff I did when I was sick",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/fd008607e991.png",
    "aspect": 1.754386,
    "widthPx": 1200,
    "heightPx": 684
  },
  {
    "id": "869e94724f7e",
    "index": 35,
    "title": "Black and white stuff",
    "category": "Black and white stuff",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/869e94724f7e.jpg",
    "aspect": 1.333333,
    "widthPx": 1600,
    "heightPx": 1200
  },
  {
    "id": "8fb0d2df1c78",
    "index": 42,
    "title": "Poop",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/8fb0d2df1c78.jpg",
    "aspect": 1.780415,
    "widthPx": 1200,
    "heightPx": 674
  },
  {
    "id": "cca747fb8b18",
    "index": 73,
    "title": "Woods",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/cca747fb8b18.jpg",
    "aspect": 1.668985,
    "widthPx": 1200,
    "heightPx": 719
  },
  {
    "id": "624867b2906e",
    "index": 74,
    "title": "Dog and girl",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/624867b2906e.jpg",
    "aspect": 1.534527,
    "widthPx": 1200,
    "heightPx": 782
  },
  {
    "id": "a1f333d17b07",
    "index": 75,
    "title": "Hug",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/a1f333d17b07.jpg",
    "aspect": 0.739167,
    "widthPx": 887,
    "heightPx": 1200
  },
  {
    "id": "1e28cb00a684",
    "index": 76,
    "title": "Cat",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/1e28cb00a684.jpg",
    "aspect": 1.777778,
    "widthPx": 1200,
    "heightPx": 675
  },
  {
    "id": "301311ce0aa1",
    "index": 77,
    "title": "Papa dog",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/301311ce0aa1.jpg",
    "aspect": 1.666667,
    "widthPx": 1200,
    "heightPx": 720
  },
  {
    "id": "50ab85b7b9ce",
    "index": 85,
    "title": "Mom and bird",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/50ab85b7b9ce.jpg",
    "aspect": 0.714167,
    "widthPx": 857,
    "heightPx": 1200
  },
  {
    "id": "926bf01f6b1e",
    "index": 86,
    "title": "Bothers",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/926bf01f6b1e.jpg",
    "aspect": 0.789167,
    "widthPx": 947,
    "heightPx": 1200
  },
  {
    "id": "b414afd81e9a",
    "index": 87,
    "title": "Dog",
    "category": "Black and white stuff",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/b414afd81e9a.jpg",
    "aspect": 1.777778,
    "widthPx": 1200,
    "heightPx": 675
  },
  {
    "id": "e6483be43e17",
    "index": 7,
    "title": "My husband",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/e6483be43e17.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "4f449030c548",
    "index": 8,
    "title": "Rat",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/4f449030c548.jpg",
    "aspect": 1.042572,
    "widthPx": 1200,
    "heightPx": 1151
  },
  {
    "id": "baccd26bd109",
    "index": 12,
    "title": "Ocean monster",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/baccd26bd109.jpg",
    "aspect": 0.8,
    "widthPx": 960,
    "heightPx": 1200
  },
  {
    "id": "183f9d387d6a",
    "index": 29,
    "title": "Haidee",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/183f9d387d6a.jpg",
    "aspect": 1.5,
    "widthPx": 1200,
    "heightPx": 800
  },
  {
    "id": "a81bdc4402ab",
    "index": 30,
    "title": "Ice skating group logo",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/a81bdc4402ab.png",
    "aspect": 1.0,
    "widthPx": 1200,
    "heightPx": 1200
  },
  {
    "id": "352fd33d2e89",
    "index": 54,
    "title": "Cookies",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/352fd33d2e89.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "2b3c83c5fc6c",
    "index": 61,
    "title": "Uncle",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": true,
    "collection": "",
    "image": "./art/assets/2b3c83c5fc6c.jpg",
    "aspect": 0.75,
    "widthPx": 900,
    "heightPx": 1200
  },
  {
    "id": "694628a89ba4",
    "index": 90,
    "title": "CBH T-shirt",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/694628a89ba4.png",
    "aspect": 2.34375,
    "widthPx": 1200,
    "heightPx": 512
  },
  {
    "id": "af0d1ace823c",
    "index": 91,
    "title": "Chengdian",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/af0d1ace823c.png",
    "aspect": 1.06383,
    "widthPx": 1200,
    "heightPx": 1128
  },
  {
    "id": "fa9ecfbf1fe9",
    "index": 92,
    "title": "CSH T-shirt design",
    "category": "Stuff I did for others",
    "note": "",
    "featured": true,
    "eyeLevel": false,
    "collection": "",
    "image": "./art/assets/fa9ecfbf1fe9.png",
    "aspect": 0.7725,
    "widthPx": 927,
    "heightPx": 1200
  },
  {
    "id": "fashion-design-1",
    "index": 10010,
    "title": "Fashion design 1",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "fashion-designs",
    "image": "./art/assets/fashion-design-1.jpg",
    "aspect": 0.5625,
    "widthPx": 675,
    "heightPx": 1200
  },
  {
    "id": "fashion-design-2",
    "index": 10011,
    "title": "Fashion design 2",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "fashion-designs",
    "image": "./art/assets/fashion-design-2.jpg",
    "aspect": 0.5625,
    "widthPx": 675,
    "heightPx": 1200
  },
  {
    "id": "fashion-design-3",
    "index": 10012,
    "title": "Fashion design 3",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "fashion-designs",
    "image": "./art/assets/fashion-design-3.jpg",
    "aspect": 0.666667,
    "widthPx": 800,
    "heightPx": 1200
  },
  {
    "id": "fashion-design-4",
    "index": 10013,
    "title": "Fashion design 4",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "fashion-designs",
    "image": "./art/assets/fashion-design-4.jpg",
    "aspect": 0.666667,
    "widthPx": 800,
    "heightPx": 1200
  },
  {
    "id": "fashion-design-5",
    "index": 10014,
    "title": "Fashion design 5",
    "category": "Stuff I did for others",
    "note": "",
    "featured": false,
    "eyeLevel": false,
    "collection": "fashion-designs",
    "image": "./art/assets/fashion-design-5.jpg",
    "aspect": 0.666667,
    "widthPx": 800,
    "heightPx": 1200
  }
];
